export  const CATERING_LOADING= 'CATERING_LOADING';
export  const CATERING_SUCCESS= 'CATERING_SUCCESS';
export  const CATERING_ERROR= 'CATERING_ERROR';


export  const CATERING_SLIDER_LOADING= 'CATERING_SLIDER_LOADING';
export  const CATERING_SLIDER_SUCCESS= 'CATERING_SLIDER_SUCCESS';
export  const CATERING_SLIDER_ERROR= 'CATERING_SLIDER_ERROR';