export  const RESERVATION_LOADING= 'RESERVATION_LOADING';
export  const RESERVATION_SUCCESS= 'RESERVATION_SUCCESS';
export  const RESERVATION_ERROR= 'RESERVATION_ERROR';




export  const RESERVATION_SLIDER_LOADING= 'RESERVATION_SLIDER_LOADING';
export  const RESERVATION_SLIDER_SUCCESS= 'RESERVATION_SLIDER_SUCCESS';
export  const RESERVATION_SLIDER_ERROR= 'RESERVATION_SLIDER_ERROR';